# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab-6/Nexys4ddrMaster.xdc

# Block Designs: bd/TwoMatrixMultiplication/TwoMatrixMultiplication.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication || ORIG_REF_NAME==TwoMatrixMultiplication} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_clk_wiz_0_0/TwoMatrixMultiplication_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_clk_wiz_0_0 || ORIG_REF_NAME==TwoMatrixMultiplication_clk_wiz_0_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_topLevel_0_0/TwoMatrixMultiplication_topLevel_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_topLevel_0_0 || ORIG_REF_NAME==TwoMatrixMultiplication_topLevel_0_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_uartlite_0_0/TwoMatrixMultiplication_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_uartlite_0_0 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_0_0/TwoMatrixMultiplication_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_0_0 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_0_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_0_1/TwoMatrixMultiplication_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_0_1 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_0_1} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_0_2/TwoMatrixMultiplication_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_0_2 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_0_2} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_0_3/TwoMatrixMultiplication_axi_gpio_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_0_3 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_0_3} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_0_4/TwoMatrixMultiplication_axi_gpio_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_0_4 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_0_4} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_0_5/TwoMatrixMultiplication_axi_gpio_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_0_5 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_0_5} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_0_6/TwoMatrixMultiplication_axi_gpio_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_0_6 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_0_6} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_0_7/TwoMatrixMultiplication_axi_gpio_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_0_7 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_0_7} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_0_8/TwoMatrixMultiplication_axi_gpio_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_0_8 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_0_8} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_8_0/TwoMatrixMultiplication_axi_gpio_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_8_0 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_8_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_8_1/TwoMatrixMultiplication_axi_gpio_8_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_8_1 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_8_1} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_8_2/TwoMatrixMultiplication_axi_gpio_8_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_8_2 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_8_2} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_8_3/TwoMatrixMultiplication_axi_gpio_8_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_8_3 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_8_3} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_8_4/TwoMatrixMultiplication_axi_gpio_8_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_8_4 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_8_4} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_8_5/TwoMatrixMultiplication_axi_gpio_8_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_8_5 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_8_5} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_8_6/TwoMatrixMultiplication_axi_gpio_8_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_8_6 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_8_6} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_8_7/TwoMatrixMultiplication_axi_gpio_8_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_8_7 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_8_7} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_8_8/TwoMatrixMultiplication_axi_gpio_8_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_8_8 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_8_8} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_17_0/TwoMatrixMultiplication_axi_gpio_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_17_0 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_17_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_0/TwoMatrixMultiplication_axi_gpio_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_18_0 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_18_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_1/TwoMatrixMultiplication_axi_gpio_18_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_18_1 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_18_1} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_2/TwoMatrixMultiplication_axi_gpio_18_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_18_2 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_18_2} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_3/TwoMatrixMultiplication_axi_gpio_18_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_18_3 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_18_3} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_4/TwoMatrixMultiplication_axi_gpio_18_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_18_4 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_18_4} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_5/TwoMatrixMultiplication_axi_gpio_18_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_18_5 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_18_5} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_6/TwoMatrixMultiplication_axi_gpio_18_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_18_6 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_18_6} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_7/TwoMatrixMultiplication_axi_gpio_18_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_axi_gpio_18_7 || ORIG_REF_NAME==TwoMatrixMultiplication_axi_gpio_18_7} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_microblaze_0_0/TwoMatrixMultiplication_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_microblaze_0_0 || ORIG_REF_NAME==TwoMatrixMultiplication_microblaze_0_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_dlmb_v10_0/TwoMatrixMultiplication_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_dlmb_v10_0 || ORIG_REF_NAME==TwoMatrixMultiplication_dlmb_v10_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_ilmb_v10_0/TwoMatrixMultiplication_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_ilmb_v10_0 || ORIG_REF_NAME==TwoMatrixMultiplication_ilmb_v10_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_dlmb_bram_if_cntlr_0/TwoMatrixMultiplication_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==TwoMatrixMultiplication_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_ilmb_bram_if_cntlr_0/TwoMatrixMultiplication_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==TwoMatrixMultiplication_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_lmb_bram_0/TwoMatrixMultiplication_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_lmb_bram_0 || ORIG_REF_NAME==TwoMatrixMultiplication_lmb_bram_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_mdm_1_0/TwoMatrixMultiplication_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_mdm_1_0 || ORIG_REF_NAME==TwoMatrixMultiplication_mdm_1_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_rst_clk_wiz_0_100M_0/TwoMatrixMultiplication_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==TwoMatrixMultiplication_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_xbar_0/TwoMatrixMultiplication_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_xbar_0 || ORIG_REF_NAME==TwoMatrixMultiplication_xbar_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_microblaze_0_axi_periph_0/TwoMatrixMultiplication_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_microblaze_0_axi_periph_0 || ORIG_REF_NAME==TwoMatrixMultiplication_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_util_vector_logic_0_0/TwoMatrixMultiplication_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_util_vector_logic_0_0 || ORIG_REF_NAME==TwoMatrixMultiplication_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_tier2_xbar_0_0/TwoMatrixMultiplication_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_tier2_xbar_0_0 || ORIG_REF_NAME==TwoMatrixMultiplication_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_tier2_xbar_1_0/TwoMatrixMultiplication_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_tier2_xbar_1_0 || ORIG_REF_NAME==TwoMatrixMultiplication_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_tier2_xbar_2_0/TwoMatrixMultiplication_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_tier2_xbar_2_0 || ORIG_REF_NAME==TwoMatrixMultiplication_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_tier2_xbar_3_0/TwoMatrixMultiplication_tier2_xbar_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TwoMatrixMultiplication_tier2_xbar_3_0 || ORIG_REF_NAME==TwoMatrixMultiplication_tier2_xbar_3_0} -quiet] -quiet

# XDC: bd/TwoMatrixMultiplication/TwoMatrixMultiplication_ooc.xdc
