# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab-6/Nexys4ddrMaster.xdc

# Block Designs: bd/DeterminantMicroBlaze/DeterminantMicroBlaze.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze || ORIG_REF_NAME==DeterminantMicroBlaze} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_clk_wiz_0_0/DeterminantMicroBlaze_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_clk_wiz_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_clk_wiz_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_DeterminantTopModule_0_0/DeterminantMicroBlaze_DeterminantTopModule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_DeterminantTopModule_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_DeterminantTopModule_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_uartlite_0_0/DeterminantMicroBlaze_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_uartlite_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_0_0/DeterminantMicroBlaze_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_1_0/DeterminantMicroBlaze_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_1_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_1_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_2_0/DeterminantMicroBlaze_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_2_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_2_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_3_0/DeterminantMicroBlaze_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_3_0 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_3_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_3_1/DeterminantMicroBlaze_axi_gpio_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_3_1 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_3_1} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_3_2/DeterminantMicroBlaze_axi_gpio_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_3_2 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_3_2} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_3_3/DeterminantMicroBlaze_axi_gpio_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_3_3 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_3_3} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_3_4/DeterminantMicroBlaze_axi_gpio_3_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_3_4 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_3_4} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_3_5/DeterminantMicroBlaze_axi_gpio_3_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_3_5 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_3_5} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_axi_gpio_3_6/DeterminantMicroBlaze_axi_gpio_3_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_axi_gpio_3_6 || ORIG_REF_NAME==DeterminantMicroBlaze_axi_gpio_3_6} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_microblaze_0_0/DeterminantMicroBlaze_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_microblaze_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_microblaze_0_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_dlmb_v10_0/DeterminantMicroBlaze_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_dlmb_v10_0 || ORIG_REF_NAME==DeterminantMicroBlaze_dlmb_v10_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_ilmb_v10_0/DeterminantMicroBlaze_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_ilmb_v10_0 || ORIG_REF_NAME==DeterminantMicroBlaze_ilmb_v10_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_dlmb_bram_if_cntlr_0/DeterminantMicroBlaze_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==DeterminantMicroBlaze_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_ilmb_bram_if_cntlr_0/DeterminantMicroBlaze_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==DeterminantMicroBlaze_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_lmb_bram_0/DeterminantMicroBlaze_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_lmb_bram_0 || ORIG_REF_NAME==DeterminantMicroBlaze_lmb_bram_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_mdm_1_0/DeterminantMicroBlaze_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_mdm_1_0 || ORIG_REF_NAME==DeterminantMicroBlaze_mdm_1_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_rst_clk_wiz_0_100M_0/DeterminantMicroBlaze_rst_clk_wiz_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==DeterminantMicroBlaze_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_xbar_0/DeterminantMicroBlaze_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_xbar_0 || ORIG_REF_NAME==DeterminantMicroBlaze_xbar_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_microblaze_0_axi_periph_0/DeterminantMicroBlaze_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_microblaze_0_axi_periph_0 || ORIG_REF_NAME==DeterminantMicroBlaze_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/DeterminantMicroBlaze/ip/DeterminantMicroBlaze_util_vector_logic_0_0/DeterminantMicroBlaze_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DeterminantMicroBlaze_util_vector_logic_0_0 || ORIG_REF_NAME==DeterminantMicroBlaze_util_vector_logic_0_0} -quiet] -quiet

# XDC: bd/DeterminantMicroBlaze/DeterminantMicroBlaze_ooc.xdc
