webtalk_init -webtalk_dir C:\\Users\\KuldeepGohil\\Desktop\\Spring2021\\CECS460\\labs\\VivadoProjects\\midtermProject\\midtermProject.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-04-24 21:40:04" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174166057_174166058_210737082_767" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "s6099cjuic7i1ndkehubc8koo" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_30" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 5600X 6-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3700 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.101 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1619314663377" -context "sdk\\\\bsp/1619314663377"
webtalk_add_data -client sdk -key hwid -value "1619313412756" -context "sdk\\\\bsp/1619314663377"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1619314663377"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1619314663377"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1619314663377"
webtalk_add_data -client sdk -key uid -value "1619314664407" -context "sdk\\\\application/1619314664407"
webtalk_add_data -client sdk -key hwid -value "1619313412756" -context "sdk\\\\application/1619314664407"
webtalk_add_data -client sdk -key bspid -value "1619314663377" -context "sdk\\\\application/1619314664407"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1619314664407"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1619314664407"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1619314664407"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1619314664407"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1619314664407"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1619314664407"
webtalk_add_data -client sdk -key projSize -value "113.64453125" -context "sdk\\\\application/1619314664407"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1619325604101"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1619325604101"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1619325604101"
webtalk_add_data -client sdk -key DebugCount -value "49" -context "sdk\\\\bsp/1619325604101"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1619325604101"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1619325604101"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1619325604101"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1619325604101"
webtalk_transmit -clientid 2432727188 -regid "174166057_174166058_210737082_767" -xml C:\\Users\\KuldeepGohil\\Desktop\\Spring2021\\CECS460\\labs\\VivadoProjects\\midtermProject\\midtermProject.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\KuldeepGohil\\Desktop\\Spring2021\\CECS460\\labs\\VivadoProjects\\midtermProject\\midtermProject.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\KuldeepGohil\\Desktop\\Spring2021\\CECS460\\labs\\VivadoProjects\\midtermProject\\midtermProject.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
