# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/KuldeepGohil/Desktop/Spring2021/CECS460/labs/VivadoProjects/midtermProject/midtermProject.srcs/sources_1/bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_5/TwoMatrixMultiplication_axi_gpio_18_5.xci
# IP: The module: 'TwoMatrixMultiplication_axi_gpio_18_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KuldeepGohil/Desktop/Spring2021/CECS460/labs/VivadoProjects/midtermProject/midtermProject.srcs/sources_1/bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_5/TwoMatrixMultiplication_axi_gpio_18_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TwoMatrixMultiplication_axi_gpio_18_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/KuldeepGohil/Desktop/Spring2021/CECS460/labs/VivadoProjects/midtermProject/midtermProject.srcs/sources_1/bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_5/TwoMatrixMultiplication_axi_gpio_18_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TwoMatrixMultiplication_axi_gpio_18_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/KuldeepGohil/Desktop/Spring2021/CECS460/labs/VivadoProjects/midtermProject/midtermProject.srcs/sources_1/bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_5/TwoMatrixMultiplication_axi_gpio_18_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'TwoMatrixMultiplication_axi_gpio_18_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/KuldeepGohil/Desktop/Spring2021/CECS460/labs/VivadoProjects/midtermProject/midtermProject.srcs/sources_1/bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_5/TwoMatrixMultiplication_axi_gpio_18_5.xci
# IP: The module: 'TwoMatrixMultiplication_axi_gpio_18_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/KuldeepGohil/Desktop/Spring2021/CECS460/labs/VivadoProjects/midtermProject/midtermProject.srcs/sources_1/bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_5/TwoMatrixMultiplication_axi_gpio_18_5_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'TwoMatrixMultiplication_axi_gpio_18_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/KuldeepGohil/Desktop/Spring2021/CECS460/labs/VivadoProjects/midtermProject/midtermProject.srcs/sources_1/bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_5/TwoMatrixMultiplication_axi_gpio_18_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TwoMatrixMultiplication_axi_gpio_18_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/KuldeepGohil/Desktop/Spring2021/CECS460/labs/VivadoProjects/midtermProject/midtermProject.srcs/sources_1/bd/TwoMatrixMultiplication/ip/TwoMatrixMultiplication_axi_gpio_18_5/TwoMatrixMultiplication_axi_gpio_18_5.xdc
# XDC: The top module name and the constraint reference have the same name: 'TwoMatrixMultiplication_axi_gpio_18_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
